"""remove last_seen

Revision ID: 7529a9bd20b3
Revises: 233f23733eea
Create Date: 2022-02-17 17:36:17.480208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7529a9bd20b3'
down_revision = '233f23733eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
