"""plants table

Revision ID: e931c8fed22e
Revises: 0070ac93b849
Create Date: 2022-02-04 15:56:04.750512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e931c8fed22e'
down_revision = '0070ac93b849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=64), nullable=True),
    sa.Column('last_watering_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_last_watering_timestamp'), 'plant', ['last_watering_timestamp'], unique=False)
    op.create_index(op.f('ix_plant_plant_name'), 'plant', ['plant_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_plant_name'), table_name='plant')
    op.drop_index(op.f('ix_plant_last_watering_timestamp'), table_name='plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
